spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment?useSSL=false
    username: root
    password: root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
app:
  pay:
    wx:
      notify_url: http://localhost/wx/pay/order/notify
      redirect_url: http://xxxx/wechat/auth
      app_id: xxxxxx
      app_secret: xxxxxxxx
      mch_id: xxxxxxx
      api_key: xxxxxx
      cert_path: apiclient_cert.p12
      pay_url: https://api.mch.wx.qq.com/pay/unifiedorder              # 统一下单url
      refund_url: https://api.mch.wx.qq.com/secapi/pay/refund          # 申请退款url
    ali:
      appid: xx
      private_key: xx
      public_key: xxx
      alipay_public_key: xxx
      openApi: https://openapi.alipay.com/gateway.do
